apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-deployment
  labels:
    app: app01
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
        - name: app01
          image: nginx
          ports:
            - containerPort: 80