apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/sdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lnxdev01
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: local-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi